# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: edrouot <edrouot@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/11 13:11:53 by edrouot           #+#    #+#              #
#    Updated: 2023/05/24 13:53:30 by edrouot          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS	= ft_isalpha.c	ft_isdigit.c	ft_isalnum.c	ft_isascii.c	ft_isprint.c	ft_strlen.c	ft_memset.c	ft_bzero.c	ft_memcpy.c	ft_strlcpy.c	ft_strlcat.c	ft_toupper.c	ft_tolower.c	ft_strchr.c	ft_strrchr.c	ft_strncmp.c	ft_memchr.c	ft_strnstr.c	ft_atoi.c	ft_calloc.c	ft_strdup.c	ft_substr.c	ft_strjoin.c	ft_strtrim.c	ft_split.c	ft_itoa.c	ft_strmapi.c	ft_striteri.c	ft_putchar_fd.c	ft_putstr_fd.c	ft_putendl_fd.c	ft_putnbr_fd.c	ft_memmove.c	ft_memcmp.c	ft_calloc.c 	

SRCS_BONUS = ft_lstnew_bonus.c	ft_lstadd_front_bonus.c	ft_lstsize_bonus.c	ft_lstlast_bonus.c	ft_lstadd_back_bonus.c	ft_lstdelone_bonus.c	ft_lstclear_bonus.c	ft_lstiter_bonus.c	ft_lstmap_bonus.c

NAME	= libft.a

OBJS	= $(SRCS:.c=.o)
OBJS_BONUS = $(SRCS_BONUS:.c=.o)

CC 	= cc

CFLAGS	= -Wall -Wextra -Werror

all:	$(NAME)

${NAME}: $(OBJS)
				@ar rc $(NAME) $(OBJS)

%.o: %.c
				@$(CC) $(CFLAGS) -c $< -o $@

clean: 
				@rm -rf $(OBJS) $(OBJS_BONUS)

fclean: clean
				@rm -f $(NAME)

re:	fclean all

bonus : $(OBJS) $(OBJS_BONUS)
				@ar rc $(NAME) $(OBJS) $(OBJS_BONUS)

.PHONY:	all clean fclean re
